const startGameBtn = document.getElementById('startGameBtn');
const nextPlayerBtn = document.getElementById('nextPlayerBtn');
const hideWordBtn = document.getElementById('hideWordBtn');
const numPlayersInput = document.getElementById('numPlayers');
const startScreen = document.getElementById('startScreen');
const gameScreen = document.getElementById('gameScreen');
const playerTurnInfo = document.getElementById('playerTurnInfo');
const displayWord = document.getElementById('displayWord');
const words = ["książka",
"chmiel", "szyszka", "sowa", "bańka", "pionek", "nitka", "skorupa", "pajęczyna", "leśniczówka",
"guzik", "pióro", "pępek", "komin", "błoto", "tętnica", "mięsień", "ścięgno", "kość", "staw",
"chrząstka", "nerw", "naczynie", "gruczoł", "hormon", "enzym", "wirus", "bakteria", "grzyb",
"pleśń", "mech", "porost", "paproć", "szkło", "plastik", "metal", "drewno", "kamień", "glina",
"cegła", "cement", "beton", "piasek", "żwir", "granit", "marmur", "wulkan", "lawina", "potok",
"źródło", "gejzer", "rafineria", "elektrownia", "turbina", "generator", "transformator",
"akumulator", "bateria", "gniazdko", "wtyczka", "żarówka", "dioda", "rezystor", "kondensator",
"tranzystor", "mikrofon", "głośnik", "słuchawki", "kamera", "projektor", "ekran", "monitor",
"klawiatura", "myszka", "router", "modem", "antena", "satelita", "teleskop", "mikroskop",
"kompas", "termometr", "barometr", "zegar", "minutnik", "stoper", "kalendarz", "mapa",
"globus", "luneta", "lornetka", "aparat", "statyw", "obiektyw", "filtr", "migawka", "lamp błyskowa",
"pędzel", "paleta", "blejtram", "ramka", "werniks", "gwasz", "akwarela", "olej", "tempera",
"fresk", "mozaika", "witraz", "rysunek", "szkic", "węgiel", "kreda", "pastel", "ołówek",
"pióro", "tusz", "atrament", "pergamin", "papirus", "kodeks", "manuskrypt", "inkunabuł",
"starodruk", "biblia", "psalm", "hymn", "pieśń", "kolęda", "kołysanka", "melodia", "harmonia",
"rytm", "takt", "tempo", "dźwięk", "echo", "szum", "szmer", "brzęk", "stukot", "grzmot", "błysk",
"płomień", "iskra", "popiół", "sadza", "dym", "para", "mgła", "rosa", "szron", "grad", "szadź",
"sople", "lód", "szkło", "diament", "rubin", "szmaragd", "szafir", "ametyst", "topaz", "opal",
"turkus", "granat", "perła", "koral", "muszla", "bursztyn", "kość słoniowa", "kość", "mąka",
"ciasto", "drożdże", "pieczywo", "bułka", "rogal", "precel", "pączek", "gofr", "naleśnik",
"pieróg", "kluska", "kasza", "ryż", "makaron", "zupa", "rosół", "barszcz", "żurek", "flaki",
"bigos", "gulasz", "kotlet", "stek", "szaszłyk", "kiełbasa", "szynka", "bekon", "pasztet",
"salceson", "kabanos", "parówka", "żeberka", "kurczak", "kaczka", "gęś", "indyk", "królik",
"dzik", "jeleń", "zając", "lis", "wilk", "niedźwiedź", "bóbr", "wydra", "borsuk", "jenot",
"ryś", "żubr", "łoś", "cielę", "koń", "osioł", "muł", "wół", "owca", "koza", "świnia", "krowa",
"pies", "kot", "chomik", "świnka morska", "królik", "papuga", "kanarek", "gołąb", "wróbel",
"bocian", "żuraw", "łabędź", "kaczka", "gęś", "kura", "kogut", "indyk", "struś", "pingwin",
"orka", "delfin", "rekin", "wieloryb", "ośmiornica", "meduza", "konik morski", "krewetka",
"krab", "homar", "rak", "żaba", "ropucha", "jaszczurka", "wąż", "krokodyl", "żółw", "gekon",
"ślimak", "pająk", "mrówka", "pszczoła", "osa", "mucha", "komar", "biedronka", "motyl",
"ćma", "ważka", "modliszka", "pasikonik", "świerszcz", "stonoga", "kleszcz", "pijawka", "dżdżownica",
"wazon", "dzbanek", "kufel", "szklanka", "filiżanka", "talerz", "miska", "widelec", "nóż",
"łyżka", "chochla", "cedzak", "sitko", "tarka", "deska", "wałek", "garnek", "patelnia", "czajnik",
"lodówka", "piekarnik", "kuchenka", "zmywarka", "pralka", "suszarka", "żelazko", "odkurzacz",
"mop", "szczotka", "gąbka", "ściereczka", "mydło", "szampon", "pasta", "szczoteczka", "ręcznik",
"lustro", "waga", "termometr", "nożyczki", "pilnik", "obcęgi", "kombinerki", "klucz",
"śrubokręt", "młotek", "piła", "wiertarka", "poziomica", "miarka", "linijka", "cyrkiel",
"ekierka", "gumka", "temperówka", "kredki", "flamaster", "pisak", "marker", "mazak", "farby",
"pędzel", "modelina", "plastelina", "klej", "taśma", "nożyczki", "spinacz", "zszywacz", "dziurkacz",
"segregator", "teczka", "koperta", "kartka", "zeszyt", "papier", "bibuła", "folia", "płótno",
"skóra", "futro", "wełna", "jedwab", "bawełna", "len", "syntetyk", "dzianina", "tkanina",
"włókno", "nić", "sznurek", "linka", "plecionka", "szydełko", "druty", "krosno", "igła",
"naprawek", "cerowanie", "haft", "koronka", "frędzel", "chwost", "kokarda", "wstążka", "łańcuszek",
"naszyjnik", "bransoletka", "kolczyki", "pierścionek", "broszka", "spinka", "krawat", "muszka",
"apaszka", "chusta", "szal", "peleryna", "płaszcz", "kurtka", "marynarka", "kamizelka", "sweter",
"golf", "koszula", "bluzka", "t-shirt", "polo", "top", "sukienka", "spódnica", "spodnie",
"jeansy", "legginsy", "szorty", "garnitur", "smoking", "frak", "mundur", "piżama", "szlafrok",
"bielizna", "skarpetki", "rajstopy", "podkolanówki", "sandały", "klapki", "trampki", "adidasy",
"kozaki", "kalosze", "glany", "szpilki", "baleriny", "mokasyny", "loafersy", "szyja", "głowa",
"ucho", "nos", "oko", "usta", "ząb", "język", "broda", "wąsy", "włosy", "brew", "rzęsa",
"policzek", "czoło", "skroń", "żuchwa", "podbródek", "kark", "ramię", "łokieć", "nadgarstek",
"dłoń", "palec", "paznokieć", "kciuk", "serce", "płuco", "wątroba", "nerka", "żołądek",
"jelito", "mózg", "rdzeń", "krew", "limfa", "skóra", "naskórek", "paznokieć", "kościec", "mięsień",
"więzadło", "ścięgno", "staw", "chrząstka", "nerw", "komórka", "tkanka", "narząd", "układ",
"organizm", "wzrok", "słuch", "węch", "smak", "dotyk", "ból", "dreszcze", "gorączka", "pot",
"łzy", "śmiech", "płacz", "uśmiech", "grymas", "gest", "spojrzenie", "szept", "krzyk", "śpiew",
"mowa", "język", "alfabet", "litera", "sylaba", "wyraz", "zdanie", "akcent", "dialekt", "gwara",
"słownictwo", "gramatyka", "ortografia", "interpunkcja", "kaligrafia", "stenografia",
"szyfr", "kod", "hasło", "zagadka", "łamigłówka", "krzyżówka", "rebus", "szarada", "anecdota",
"bajka", "baśń", "legenda", "mit", "epos", "poemat", "wiersz", "sonet", "oda", "hymn",
"ballada", "dramat", "komedia", "tragedia", "farsa", "opera", "operetka", "musical", "balet",
"pantomima", "cyrk", "pokaz", "sztuczka", "magik", "klown", "akrobata", "żongler", "iluzjonista",
"wróżka", "jasnowidz", "horoskop", "przeznaczenie", "los", "szczęście", "pech", "fortuna",
"przypadek", "serendipity", "karma", "reinkarnacja", "duch", "widmo", "zjawa", "potwór",
"demon", "anioł", "niebo", "piekło", "czyściec", "raj", "eden", "arka", "potop", "bóg",
"bóstwo", "święty", "prorok", "mesjasz", "zbawiciel", "apostata", "heretyk", "idol", "fetysz",
"amulet", "talizman", "czary", "rytuał", "obrzęd", "ofiara", "modlitwa", "medytacja", "mantra",
"joga", "zen", "buddyzm", "chrześcijaństwo", "islam", "judaizm", "hinduizm", "sikhizm",
"dżinizm", "szintoizm", "taoizm", "konfucjanizm", "ateizm", "agnostycyzm", "humanizm",
"filozofia", "etyka", "moralność", "logika", "metafizyka", "estetyka", "poznanie", "prawda",
"fałsz", "dobro", "zło", "piękno", "brzydota", "idea", "pojęcie", "teoria", "hipoteza", "dowód",
"eksperyment", "badanie", "analiza", "synteza", "dedukcja", "indukcja", "wniosek", "obserwacja",
"doświadczenie", "pomiar", "obliczenie", "algorytm", "program", "kod", "błąd", "debugowanie",
"kompilator", "interpreter", "sieć", "serwer", "klient", "protokół", "szyfrowanie", "haszowanie",
"algorytm", "struktura", "dane", "baza danych", "chmura", "wirtualizacja", "wirus", "firewall",
"antywirus", "bezpieczeństwo", "prywatność", "anonimowość", "tożsamość", "hasło", "login",
"profil", "konto", "awatar", "nick", "pseudonim", "forum", "blog", "czat", "email", "wiadomość",
"powiadomienie", "subskrypcja", "kanał", "feed", "podcast", "streaming", "multimedia", "grafika",
"animacja", "wideo", "audio", "plik", "folder", "katalog", "dysk", "pamięć", "procesor",
"karta", "płyta", "port", "kabel", "przejściówka", "adapter", "ładowarka", "zasilacz",
"bateria", "gniazdko", "przedłużacz", "listwa", "bezpiecznik", "transformator", "latarka",
"zapłon", "silnik", "bieg", "sprzęgło", "hamulec", "kierownica", "pedał", "opona", "felga",
"amortyzator", "zawieszenie", "układ", "wydech", "chłodzenie", "smarowanie", "paliwo", "benzyna",
"ropa", "gaz", "elektryczność", "hybryda", "akumulator", "stacja", "ładowanie", "autostrada",
"droga", "jezdnia", "chodnik", "pobocze", "parking", "garaż", "tunel", "wiadukt", "rondo",
"skrzyżowanie", "światła", "znak", "fotoradar", "mandat", "wypadek", "kolizja", "stłuczka",
"policja", "ambulans", "straż pożarna", "pomoc", "pierwsza pomoc", "apteczka", "opatrunek",
"bandaż", "plaster", "dezynfekcja", "rana", "siniak", "oparzenie", "złamanie", "zwichnięcie",
"stłuczenie", "ból", "gorączka", "kaszel", "katar", "grypa", "przeziębienie", "alergia",
"astma", "cukrzyca", "serce", "wylew", "zawał", "rak", "nowotwór", "terapia", "rehabilitacja",
"operacja", "szczepionka", "antybiotyk", "witamina", "minerał", "dieta", "odżywianie", "trening",
"ćwiczenie", "siłownia", "basen", "bieganie", "jazda", "wędrówka", "spacer", "oddech", "puls",
"krążenie", "ciśnienie", "temperatura", "sen", "drzemka", "pobudka", "zmęczenie", "relaks",
"odpoczynek", "urlop", "weekend", "święto", "ceremonia", "obrzęd", "rytuał", "uroczystość",
"parada", "pochód", "marsz", "protest", "strajk", "wiec", "demonstracja", "rewolucja", "wojna",
"pokój", "rozejm", "traktat", "umowa", "negocjacje", "dyplomacja", "polityka", "wybory",
"głosowanie", "partia", "rząd", "parlament", "senat", "sejm", "ministrerstwo", "prezydent",
"premier", "ambasador", "konsul", "dyplomata", "szpieg", "agent", "misja", "zadanie", "cel",
"przeznaczenie", "decyzja", "wybór", "ryzyko", "szansa", "sukces", "porażka", "zwycięstwo",
"remis", "przegrana", "medal", "puchar", "nagroda", "dyplom", "certyfikat", "licencja",
"pozwolenie", "zgoda", "zakaz", "nakaz", "zasada", "reguła", "prawo", "ustawa", "kodeks",
"rozporządzenie", "dekret", "apel", "petycja", "prośba", "żądanie", "groźba", "obietnica",
"zapowiedź", "ostrzeżenie", "rada", "porada", "wskazówka", "instrukcja", "przepis", "recepta",
"rozwiązanie", "odpowiedź", "pytanie", "zagadka", "tajemnica", "sekret", "spisek", "intryga",
"intencja", "motyw", "przyczyna", "skutek", "rezultat", "konsekwencja", "wynik", "proces",
"etap", "faza", "cykl", "sekwencja", "kolejność", "hierarchia", "struktura", "system",
"organizacja", "instytucja", "fundacja", "stowarzyszenie", "unia", "liga", "federacja",
"konfederacja", "imperium", "królestwo", "republika", "demokracja", "monarchia", "tyrania",
"oligarchia", "anarchia", "utopia", "dystopia", "rewolucja", "ewolucja", "postęp", "rozwój",
"kryzys", "katastrofa", "klęska", "tragedia", "farsa", "ironia", "sarkazm", "humor", "żart",
"kawał", "dowcip", "śmiech", "radość", "szczęście", "optymizm", "pesymizm", "nadzieja",
"zrezygnowanie", "smutek", "żałoba", "rozpacz", "gniew", "złość", "frustracja", "agresja",
"nienawiść", "miłość", "przyjaźń", "życzliwość", "empatia", "współczucie", "tolerancja",
"szacunek", "zaufanie", "lojalność", "uczciwość", "sprawiedliwość", "odwaga", "bohaterstwo",
"strach", "lęk", "fobia", "panika", "trema", "obawa", "niepewność", "wątpliwość", "podejrzenie",
"zazdrość", "zawiść", "chciwość", "lenistwo", "pijaństwo", "nałóg", "uzależnienie", "lekomania",
"hazard", "kłamstwo", "oszustwo", "zdrada", "fałsz", "obłuda", "hipokryzja", "pyszałek",
"arogancja", "duma", "skromność", "pokora", "grzeczność", "uprzejmość", "kultura", "savoir-vivre",
"etykieta", "tradycja", "zwyczaj", "obyczaj", "rytuał", "ceremonia", "symbol", "herb", "flaga",
"hymn", "godło", "emblemat", "znak", "gest", "mimika", "szept", "krzyk", "śmiech", "płacz",
"cisza", "hałas", "melodia", "rytm", "taniec", "śpiew", "muzyka", "instrument", "nuta",
"akord", "orkiestra", "chór", "solista", "koncert", "festiwal", "widowisko", "spektakl",
"przedstawienie", "sztuka", "teatr", "kino", "film", "serial", "odcinek", "sezon", "premiera",
"recenzja", "krytyka", "aplauz", "brawa", "owacja", "gwiazda", "aktor", "aktorka", "reżyser",
"scenarzysta", "producent", "kostium", "scenografia", "makijaż", "oświetlenie", "dźwięk",
"montaż", "efekt", "wizualny", "specjalny", "animacja", "kreskówka", "bajka", "dokument",
"reportaż", "wiadomości", "audycja", "program", "kanał", "stacja", "antena", "radio", "telewizor",
    "ziemia", "księżyc", "słońce", "planeta", "gwiazda", "galaktyka", "wszechświat", "kosmos",
"astronauta", "rakieta", "satelita", "teleskop", "mikroskop", "kometa", "meteoryt", "asteroid",
"mgławica", "czarna dziura", "supernova", "orbita", "grawitacja", "prędkość", "czas", "przestrzeń",
"energia", "materia", "atom", "cząsteczka", "pierwiastek", "związek", "reakcja", "chemia", "fizyka",
"biologia", "geologia", "astronomia", "matematyka", "informatyka", "logika", "filozofia", "historia",
"geografia", "ekonomia", "polityka", "prawo", "socjologia", "psychologia", "antropologia", "archeologia",
"sztuka", "literatura", "muzyka", "teatr", "kino", "taniec", "malarstwo", "rzeźba", "architektura",
"fotografia", "moda", "design", "kuchnia", "gastronomia", "restauracja", "bar", "kawiarnia", "piekarnia",
"cukiernia", "sklep", "supermarket", "rynek", "bazar", "galeria", "muzeum", "biblioteka", "szkoła",
"uczelnia", "uniwersytet", "akademia", "instytut", "laboratorium", "szpital", "przychodnia", "apteka",
"policja", "straż pożarna", "pogotowie", "wojsko", "polityk", "prezydent", "premier", "minister",
"poseł", "senator", "dyplomata", "ambasador", "konsul", "urzędnik", "nauczyciel", "lekarz", "pielęgniarka",
"inżynier", "programista", "artysta", "muzyk", "pisarz", "aktor", "sportowiec", "kucharz", "piekarz",
"fryzjer", "mechanik", "budowlaniec", "rolnik", "ogrodnik", "kierowca", "pilot", "marynarz", "żołnierz",
"policjant", "strażak", "ratownik", "detektyw", "szpieg", "bohater", "zbrodniarz", "ofiara", "świadek",
"sędzia", "adwokat", "prokurator", "więzień", "strażnik", "terrorysta", "rebeliant", "rewolucjonista",
"król", "królowa", "książę", "księżniczka", "rycerz", "zamek", "pałac", "twierdza", "wieża", "lochy",
"smok", "elf", "krasnolud", "wampir", "wilkołak", "potwór", "duch", "zjawa", "czarodziej", "wróżka",
"magia", "czary", "eliksir", "amulet", "talizman", "księga", "baśń", "legenda", "mit", "opowieść",
"wiersz", "piosenka", "melodia", "rytm", "akord", "instrument", "gitara", "fortepian", "skrzypce",
"bęben", "trąbka", "flet", "klarnet", "saksofon", "akordeon", "harmonijka", "głośnik", "słuchawki",
"mikrofon", "aparat", "kamera", "obiektyw", "statyw", "lampa", "blask", "cień", "światło", "ciemność",
"kolor", "barwa", "odcień", "tęcza", "obraz", "ramka", "lustro", "wazon", "świeca", "lampion",
"latarka", "ognisko", "kominek", "ogień", "dym", "popiół", "iskra", "płomień", "żar", "popiół",
"drewno", "węgiel", "gaz", "ropa", "benzyna", "paliwo", "silnik", "bieg", "hamulec", "sprzęgło",
"kierownica", "opona", "felga", "zawieszenie", "amortyzator", "wydech", "chłodzenie", "smarowanie",
"akumulator", "bateria", "prąd", "napięcie", "opór", "obwód", "elektronika", "robot", "cyborg",
"sztuczna inteligencja", "algorytm", "program", "kod", "błąd", "wirus", "haker", "sieć", "internet",
"strona", "portal", "forum", "blog", "czat", "email", "wiadomość", "połączenie", "login", "hasło",
"profil", "awatar", "zdjęcie", "wideo", "audio", "plik", "folder", "dysk", "pamięć", "procesor",
"klawiatura", "myszka", "ekran", "monitor", "drukarka", "skaner", "kopierka", "telefon", "smartfon",
"tablet", "laptop", "komputer", "router", "modem", "kabel", "wtyczka", "gniazdko", "przedłużacz",
"transformator", "latarka", "kompas", "mapa", "globus", "teleskop", "mikroskop", "lupa", "lornetka",
"zegarek", "stoper", "timer", "kalendarz", "termometr", "barometr", "higrometr", "waga", "miarka",
"linijka", "cyrkiel", "kątomierz", "ołów", "długopis", "pióro", "atrament", "gumka", "zeszyt",
"książka", "słownik", "encyklopedia", "podręcznik", "magazyn", "gazeta", "list", "koperta", "znaczek",
"paczka", "prezent", "kwiat", "roślina", "drzewo", "krzew", "trawa", "mech", "porost", "grzyb",
"owoc", "warzywo", "zboże", "chleb", "mleko", "mięso", "ryba", "ser", "jajko", "cukier", "sól",
"pieprz", "przyprawa", "zioło", "herbata", "kawa", "sok", "woda", "piwo", "wino", "spirytus",
"szampan", "tort", "ciastko", "czekolada", "lody", "słodycze", "chipsy", "orzechy", "bakalie",
"kanapka", "zupa", "sałatka", "pizza", "burger", "frytki", "makaron", "ryż", "kasza", "ziemniak",
"chleb", "bułka", "rogalik", "pączek", "naleśnik", "pieróg", "kluska", "gofr", "naleśnik", "pasztet",
"kiełbasa", "szynka", "bekon", "stek", "kotlet", "gulasz", "bigos", "flaki", "rosół", "barszcz",
"żurek", "grzyby", "cebula", "czosnek", "marchew", "pietruszka", "seler", "papryka", "pomidor",
"ogórek", "kapusta", "brokuł", "kalafior", "szpinak", "sałata", "rzodkiewka", "burak", "fasola",
"groch", "soczewica", "kukurydza", "ziemniak", "batat", "dynia", "cukinia", "bakłażan", "awokado",
"cytryna", "pomarańcza", "mandarynka", "grejpfrut", "banan", "jabłko", "gruszka", "śliwka", "wiśnia",
"czereśnia", "truskawka", "malina", "jeżyna", "jagoda", "borówka", "poziomka", "winogrono",
"arbuz", "melon", "kiwi", "ananas", "mango", "papaja", "liczi", "kokos", "figa", "daktyl", "migdał",
"orzech", "pistacja", "nasiono", "ziarno", "pestka", "krzew", "łąka", "las", "góra", "dolina",
"wzgórze", "szczyt", "jaskinia", "wąwóz", "kanion", "klif", "plaża", "wydma", "pustynia", "oaza",
"rzeka", "jezioro", "morze", "ocean", "zatoka", "kanał", "wyspa", "półwysep", "kontynent", "archipelag",
"lodowiec", "biegun", "równik", "zwrotnik", "horyzont", "niebo", "chmura", "deszcz", "śnieg",
"grad", "burza", "piorun", "grzmot", "wiatr", "wichura", "cyklon", "tornado", "trzęsienie ziemi",
"tsunami", "powódź", "susza", "pożar", "wulkan", "lawina", "potop", "erupcja", "kataklizm", "klęska",
"szczęście", "radość", "smutek", "gniew", "strach", "miłość", "nienawiść", "przyjaźń", "zazdrość",
"zawiść", "duma", "pokora", "odwaga", "tchórzostwo", "uczciwość", "kłamstwo", "zdrada", "lojalność",
"sprawiedliwość", "niesprawiedliwość", "prawda", "fałsz", "dobro", "zło", "piękno", "brzydota",
"harmonia", "chaos", "porządek", "bałagan", "czystość", "brud", "higiena", "zdrowie", "choroba",
"ból", "cierpienie", "leczenie", "terapia", "rehabilitacja", "operacja", "szczepionka", "lek",
"witamina", "dieta", "sport", "trening", "ćwiczenie", "relaks", "odpoczynek", "sen", "marzenie",
"koszmar", "budzik", "poranek", "dzień", "wieczór", "noc", "świt", "zmierzch", "godzina", "minuta",
"sekunda", "tydzień", "miesiąc", "rok", "stulecie", "epoka", "era", "wiek", "historia", "przyszłość",
"teraźniejszość", "przeszłość", "pamięć", "wspomnienie", "zapomnienie", "nauka", "edukacja",
"egzamin", "test", "ocena", "dyplom", "certyfikat", "licencja", "pozwolenie", "zakaz", "nakaz",
"prawo", "zasada", "reguła", "kodeks", "ustawa", "sąd", "więzienie", "kara", "grzywna", "wyrok",
"adwokat", "prokurator", "sędzia", "więzień", "policja", "żołnierz", "broń", "walka", "bitwa",
"wojna", "pokój", "rozejm", "traktat", "umowa", "negocjacje", "dyplomacja", "granica", "państwo",
"naród", "kultura", "tradycja", "zwyczaj", "obyczaj", "rytuał", "ceremonia", "święto", "obrzęd",
"symbol", "flaga", "godło", "hymn", "religia", "kościół", "modlitwa", "wiara", "nadzieja",
"miłość", "duchowość", "medytacja", "karma", "przeznaczenie", "los", "szczęście", "pech",
"fortuna", "przypadek", "serendipity", "magia", "czary", "iluzja", "sztuczka", "tajemnica",
"zagadka", "łamigłówka", "krzyżówka", "rebus", "rozwiązanie", "pomysł", "plan", "projekt",
"budowa", "remont", "narzędzie", "młotek", "śrubokręt", "piła", "wiertarka", "poziomica", "miarka",
"klucz", "zamek", "kłódka", "skrzynia", "pudełko", "torba", "walizka", "plecak", "parasol",
"latarka", "okulary", "klucze", "portfel", "torebka", "zegarek", "biżuteria", "naszyjnik",
"pierścionek", "kolczyki", "bransoletka", "spinka", "krawat", "muszka", "apaszka", "chusta",
"szal", "peleryna", "płaszcz", "kurtka", "marynarka", "kamizelka", "sweter", "golf", "koszula",
"bluzka", "t-shirt", "polo", "top", "sukienka", "spódnica", "spodnie", "jeansy", "legginsy",
"szorty", "garnitur", "smoking", "mundur", "piżama", "szlafrok", "bielizna", "skarpetki", "rajstopy",
"buty", "sandały", "klapki", "trampki", "adidasy", "kozaki", "kalosze", "glany", "szpilki",
"baleriny", "mokasyny", "szyja", "głowa", "ucho", "nos", "oko", "usta", "ząb", "język", "broda",
"wąsy", "włosy", "brew", "rzęsa", "policzek", "czoło", "skroń", "żuchwa", "podbródek", "kark",
"ramię", "łokieć", "nadgarstek", "dłoń", "palec", "paznokieć", "kciuk", "serce", "płuco",
"wątroba", "nerka", "żołądek", "jelito", "mózg", "rdzeń", "krew", "limfa", "skóra", "naskórek",
"mięsień", "więzadło", "ścięgno", "staw", "chrząstka", "nerw", "komórka", "tkanka", "narząd",
"układ", "organizm", "wzrok", "słuch", "węch", "smak", "dotyk", "ból", "dreszcze", "gorączka",
"pot", "łzy", "śmiech", "płacz", "uśmiech", "grymas", "gest", "spojrzenie", "szept", "krzyk", "sztorm", "huragan", "tajfun", "tornado", "cyklon", "monsun", "bryza", "cisza", "słońce",
"światło", "cień", "mrok", "ciemność", "zorza", "błyskawica", "grzmot", "tęcza", "rosa",
"szron", "grad", "szadź", "lód", "szkło", "lustro", "odbicie", "widok", "panorama", "krajobraz",
"pejzaż", "portret", "autoportret", "miniatura", "fresk", "mozaika", "gobelin", "ceramika",
"porcelana", "glina", "gips", "marmur", "granit", "piaskowiec", "wapień", "bazalt", "wulkan",
"lawina", "potok", "źródło", "gejzer", "wodospad", "kaskada", "prąd", "fala", "wir", "otwarta przestrzeń",
"labirynt", "tunel", "jama", "grota", "jaskinia", "schron", "okop", "bunkier", "forteca",
"bastion", "wieża", "iglica", "kopuła", "dach", "podłoga", "sufit", "ściana", "fundament",
"balkon", "taras", "weranda", "ganek", "altana", "wiata", "szopa", "stodoła", "chlew", "kurnik",
"obora", "stajnia", "ul", "pasieka", "silos", "spichlerz", "młyn", "tartak", "kuźnia", "odlewnia",
"kopalnia", "szyb", "sztolnia", "sztuczne jezioro", "tama", "kanał", "śluzowiec", "most", "wiadukt",
"tunel", "rondo", "skrzyżowanie", "autostrada", "droga", "ścieżka", "szlak", "trakt", "jezdnia",
"chodnik", "pobocze", "parking", "garaż", "stacja", "przystanek", "dworzec", "lotnisko", "port",
"nabrzeże", "molo", "latarnia", "semafor", "sygnał", "znak", "tablica", "ogłoszenie", "reklama",
"bilbord", "neon", "afisz", "ulotka", "plakat", "album", "katalog", "broszura", "folder", "mapa",
"globus", "kompas", "busola", "lornetka", "luneta", "aparat", "obiektyw", "filtr", "migawka",
"przysłona", "ekspozycja", "statyw", "lampa", "odbłyśnik", "parasolka", "softbox", "blendowanie",
"retusz", "montaż", "kolaż", "grafika", "animacja", "modelowanie", "renderowanie", "teksturowanie",
"oświetlenie", "dźwięk", "muzyka", "rytm", "melodia", "harmonia", "akord", "nuta", "skala",
"tonacja", "tempo", "takt", "orkiestra", "chór", "zespół", "solista", "dyrygent", "kompozytor",
"koncert", "festiwal", "próba", "występ", "audycja", "program", "kanał", "stacja", "telewizor",
"radio", "internet", "strona", "portal", "blog", "forum", "czat", "email", "wiadomość", "sms",
"mms", "połączenie", "komórka", "smartfon", "tablet", "laptop", "komputer", "drukarka", "skaner",
"kopiarka", "faks", "telefon", "router", "modem", "kabel", "wtyczka", "gniazdko", "przedłużacz",
"ładowarka", "zasilacz", "bateria", "akumulator", "ogniwo", "przewód", "izolacja", "obwód",
"bezpiecznik", "kondensator", "rezystor", "dioda", "tranzystor", "mikroukład", "płyta", "procesor",
"pamięć", "dysk", "pendrive", "karta pamięci", "klawiatura", "myszka", "touchpad", "ekran dotykowy",
"głośnik", "słuchawki", "mikrofon", "kamera", "projektor", "robot", "dron", "sztuczna inteligencja",
"algorytm", "kod", "programowanie", "język", "biblioteka", "framework", "system", "aplikacja",
"wirus", "haker", "bezpieczeństwo", "szyfrowanie", "hasło", "login", "profil", "konto", "chmura",
"serwer", "domena", "hosting", "strona", "portal", "sieć", "internet", "intranet", "ekstranet",
"router", "modem", "antena", "satelita", "telewizja", "radiofonia", "transmisja", "audycja",
"reportaż", "dokument", "serial", "film", "gra", "konsola", "joystick", "pad", "kontrola",
"poziom", "misja", "zadanie", "punktacja", "ranking", "czempion", "zwycięzca", "pokonany", "remis",
"zasada", "reguła", "instrukcja", "podręcznik", "poradnik", "słownik", "encyklopedia", "atlas",
"globus", "mapa", "plan", "szkic", "diagram", "tabela", "wykres", "graf", "formularz", "raport",
"sprawozdanie", "analiza", "synteza", "dedukcja", "indukcja", "wniosek", "hipoteza", "teoria",
"dowód", "eksperyment", "obserwacja", "pomiar", "obliczenie", "wynik", "rezultat", "konsekwencja",
"przyczyna", "skutek", "relacja", "związek", "rola", "funkcja", "cel", "przeznaczenie", "wybór",
"decyzja", "ryzyko", "szansa", "sukces", "porażka", "nagroda", "kara", "medal", "puchar",
"dyplom", "certyfikat", "licencja", "pozwolenie", "zgoda", "odmowa", "zakaz", "nakaz", "apel",
"petycja", "prośba", "żądanie", "groźba", "obietnica", "nadzieja", "wiara", "zaufanie", "lojalność",
"zdrada", "kłamstwo", "oszustwo", "fałsz", "obłuda", "hipokryzja", "arogancja", "duma", "skromność",
"pokora", "uprzejmość", "grzeczność", "kultura", "etykieta", "savoir-vivre", "obyczaj", "tradycja",
"rytuał", "ceremonia", "święto", "uroczystość", "parada", "pochód", "marsz", "protest", "strajk",
"wiec", "demonstracja", "rewolucja", "ewolucja", "postęp", "rozwój", "kryzys", "katastrofa", "klęska",
"tragedia", "komedia", "farsa", "ironia", "sarkazm", "humor", "żart", "kawał", "dowcip", "zabawa",
"radość", "szczęście", "optymizm", "pesymizm", "smutek", "żałoba", "rozpacz", "gniew", "złość",
"frustracja", "agresja", "nienawiść", "miłość", "przyjaźń", "życzliwość", "empatia", "współczucie",
"tolerancja", "szacunek", "sprawiedliwość", "uczciwość", "odwaga", "tchórzostwo", "strach", "lęk",
"fobia", "panika", "trema", "obawa", "niepewność", "wątpliwość", "podejrzenie", "zazdrość", "zawiść",
"chciwość", "lenistwo", "pijaństwo", "nałóg", "uzależnienie", "lekomania", "hazard", "praca",
"zawód", "kariera", "pensja", "wynagrodzenie", "dochód", "zysk", "strata", "podatek", "budżet",
"konto", "bank", "gotówka", "karta", "kredyt", "dług", "inwestycja", "kapitał", "rynek", "giełda",
"akcja", "obligacja", "dywidenda", "inflacja", "deflacja", "recesja", "kryzys", "gospodarka",
"ekonomia", "finanse", "biznes", "przedsiębiorstwo", "firma", "korporacja", "startup", "mała firma",
"klient", "konsument", "sprzedawca", "producent", "dostawca", "hurtownik", "detalista", "magazyn",
"fabryka", "produkcja", "montaż", "automatyzacja", "robotyka", "technologia", "innowacja", "wynalazek",
"odkrycie", "badanie", "rozwój", "prototyp", "patent", "licencja", "znak towarowy", "marketing",
"reklama", "promocja", "kampania", "public relations", "wizerunek", "reputacja", "marka",
"identyfikacja", "logo", "slogan", "hasło", "strategia", "planowanie", "zarządzanie", "organizacja",
"struktura", "zespół", "lider", "menedżer", "pracownik", "szef", "kierownik", "dyrektor", "prezes",
"rada", "komisja", "delegacja", "spotkanie", "narada", "prezentacja", "projekt", "termin",
"budżet", "ryzyko", "kontrola", "audyt", "raport", "analiza", "decyzja", "negocjacje", "kontrakt",
"umowa", "faktura", "paragon", "rachunek", "kwit", "dowód", "dokument", "akt", "zapis", "notatka",
"kartoteka", "archiwum", "biblioteka", "książnica", "czytelnia", "regal", "półka", "książka",
"pismo", "artykuł", "esej", "rozprawa", "rozprawa", "dyskusja", "debata", "przemówienie",
"prelekcja", "wykład", "seminarium", "warsztaty", "szkolenie", "kurs", "egzamin", "test",
"ocena", "stopień", "dyplom", "świadectwo", "certyfikat", "akademia", "uniwersytet", "liceum",
"szkoła", "przedszkole", "żłobek", "nauczyciel", "profesor", "student", "uczeń", "wychowawca",
"dyrektor", "rektor", "dziekan", "kadra", "personal", "zespół", "grupa", "klasa", "klub",
"stowarzyszenie", "fundacja", "organizacja", "instytucja", "korporacja", "spółka", "firma",
"przedsiębiorstwo", "biuro", "sekretariat", "recepcja", "poczekalnia", "korytarz", "gabinet",
"sala", "audytorium", "scena", "widownia", "kulisy", "garderoba", "charakteryzatornia", "rekwizytornia",
"dekoracja", "kostium", "peruka", "maska", "rekwizyt", "charakteryzacja", "scenariusz", "libretto",
"partytura", "dyrygent", "orkiestra", "chór", "balet", "taniec", "choreografia", "scenografia",
"kostiumografia", "reżyseria", "produkcja", "realizacja", "filmowanie", "montaż", "postprodukcja",
"efekt", "wizualny", "specjalny", "dźwięk", "dubbing", "lektor", "napisy", "tłumaczenie", "adaptacja",
"remake", "sequel", "prequel", "spin-off", "epizod", "seria", "sezon", "odcinek", "finał",
"premiera", "recenzja", "krytyka", "nominacja", "nagroda", "oskar", "złoty glob", "palma", "lew"];

let currentWord = "";
let numPlayers = 0;
let spyPlayerIndex = -1;
let currentPlayer = 1;

startGameBtn.addEventListener('click', () => {
    numPlayers = parseInt(numPlayersInput.value);
    if (isNaN(numPlayers) || numPlayers < 2) {
        alert("Mimimum dwóch graczy xd");
        return;
    }
    
    spyPlayerIndex = Math.floor(Math.random() * numPlayers) + 1; 
    currentWord = words[Math.floor(Math.random() * words.length)]; 

    startScreen.style.display = 'none';
    gameScreen.style.display = 'block';
    nextPlayer();
});

nextPlayerBtn.addEventListener('click', () => {
    nextPlayer();
});

hideWordBtn.addEventListener('click', () => {
    displayWord.textContent = "Hasło zostało ukryte. Teraz podaj telefon dalej";
    hideWordBtn.style.display = 'none';
    nextPlayerBtn.style.display = 'block';
});

function nextPlayer() {
    if (currentPlayer > numPlayers) {
        playerTurnInfo.textContent = "Gramy!";
        displayWord.textContent = "";
        nextPlayerBtn.style.display = 'none';
        hideWordBtn.style.display = 'none';
        return;
    }

    playerTurnInfo.textContent = `Gracz ${currentPlayer}, weź telefon.`;
    displayWord.textContent = "Naciśnij 'Ukryj Hasło' po zapamiętaniu!";
    nextPlayerBtn.style.display = 'none';
    hideWordBtn.style.display = 'none'; 

    
    setTimeout(() => {
        if (currentPlayer === spyPlayerIndex) {
            displayWord.textContent = "Impostor!!!";
        } else {
            displayWord.textContent = `Hasło to: ${currentWord}`;
        }
        hideWordBtn.style.display = 'block';
    }, 3000);

    currentPlayer++;
}